<center>
<img src="https://laelgelcpublic.s3.sa-east-1.amazonaws.com/lael_50_years_narrow_white.png.no_years.400px_96dpi.png" width="300" alt="LAEL 50 years logo">
<h3>APPLIED LINGUISTICS GRADUATE PROGRAMME (LAEL)</h3>
</center>
<hr>

# Corpus Linguistics - Study 1 - Phase 2 - Ednalvo

This document aims to organise the data for prompt engineering tests.

## Processing 1

### Rename text files using 5-digit essay IDs

In [1]:
from pathlib import Path
import re

dataset_dir = Path("corpus/01_dataset")

for txt_file in dataset_dir.glob("*.txt"):
    match = re.match(r"^(\d{5})", txt_file.name)

    if not match:
        print(f"Skipped: {txt_file.name}")
        continue

    new_name = f"{match.group(1)}.txt"
    new_path = txt_file.with_name(new_name)

    if txt_file == new_path:
        print(f"Already renamed: {txt_file.name}")
        continue

    if new_path.exists():
        print(f"Skipped because target already exists: {txt_file.name} -> {new_name}")
        continue

    txt_file.rename(new_path)
    print(f"Renamed: {txt_file.name} -> {new_name}")

Renamed: 34844 (0498-016) - cópia.txt -> 34844.txt
Renamed: 34841 (0495-021) - cópia.txt -> 34841.txt
Skipped: quadro_de_redacao_e_scores_atribuidos_pela_banca.txt
Renamed: 34714 (0433-004).txt -> 34714.txt
Renamed: 37681 (0477-016) - cópia.txt -> 37681.txt
Renamed: 33991 (0455-017) - cópia.txt -> 33991.txt
Renamed: 33787 (0439-033) - cópia.txt -> 33787.txt
Renamed: 44497 (0517-038).txt -> 44497.txt
Renamed: 34811 (0517-014) - cópia.txt -> 34811.txt
Renamed: 33930 (0479-009) - cópia.txt -> 33930.txt
Renamed: 36560 (0502-031) - cópia.txt -> 36560.txt
Renamed: 35240 (0502-029) - cópia.txt -> 35240.txt
Renamed: 34292 (0432-005) - cópia.txt -> 34292.txt
Renamed: 35121 (0528-022) - cópia.txt -> 35121.txt
Renamed: 33856 (0470-011) - cópia.txt -> 33856.txt
Renamed: 33493 (0401-032) - cópia.txt -> 33493.txt
Renamed: 33908 (0446-031) - cópia.txt -> 33908.txt
Renamed: 33870 (0517-018) - cópia.txt -> 33870.txt
Renamed: 33083 (0496-015) - cópia.txt -> 33083.txt

### Create essay scores DataFrame

```
| high<br>De 24 a 30 scores<br>(8 a 10) | medium<br>De 18 a 23,5 scores<br>(6 a 7,83) | low<br>De 0 a 17,5 scores<br>(0 a 5,83) |
|----------------------------------------------------|---------------------------------------------------|-------------------------------------------------------------|
| 36560 (28 s)                                       | 33493 (18 s)                                      | 34714 (8 s)                                                 |
| 44497 (28 s)                                       | 33083 (20 s)                                      | 33787 (9 s)                                                 |
| 34811 (26 s)                                       | 33991 (21,5 s)                                    | 33856 (10,5 s)                                              |
| 37681 (26 s)                                       | 34292 (19 s)                                      | 33870 (13 s)                                                |
| 35240 (25 s)                                       | 34841 (23 s)                                      | 33908 (14 s)                                                |
| 34844 (24,5 s)                                     | 35121 (21 s)                                      | 33930 (17 s)                                                |
```

In [3]:
import pandas as pd

essay_scores_data = [
    {"Essay": "36560", "Score": 28, "Band": "high"},
    {"Essay": "44497", "Score": 28, "Band": "high"},
    {"Essay": "34811", "Score": 26, "Band": "high"},
    {"Essay": "37681", "Score": 26, "Band": "high"},
    {"Essay": "35240", "Score": 25, "Band": "high"},
    {"Essay": "34844", "Score": 24.5, "Band": "high"},

    {"Essay": "33493", "Score": 18, "Band": "medium"},
    {"Essay": "33083", "Score": 20, "Band": "medium"},
    {"Essay": "33991", "Score": 21.5, "Band": "medium"},
    {"Essay": "34292", "Score": 19, "Band": "medium"},
    {"Essay": "34841", "Score": 23, "Band": "medium"},
    {"Essay": "35121", "Score": 21, "Band": "medium"},

    {"Essay": "34714", "Score": 8, "Band": "low"},
    {"Essay": "33787", "Score": 9, "Band": "low"},
    {"Essay": "33856", "Score": 10.5, "Band": "low"},
    {"Essay": "33870", "Score": 13, "Band": "low"},
    {"Essay": "33908", "Score": 14, "Band": "low"},
    {"Essay": "33930", "Score": 17, "Band": "low"},
]

essay_scores_df = pd.DataFrame(essay_scores_data)

essay_scores_df

    Essay  Score    Band
0   36560   28.0    high
1   44497   28.0    high
2   34811   26.0    high
3   37681   26.0    high
4   35240   25.0    high
5   34844   24.5    high
6   33493   18.0  medium
7   33083   20.0  medium
8   33991   21.5  medium
9   34292   19.0  medium
10  34841   23.0  medium
11  35121   21.0  medium
12  34714    8.0     low
13  33787    9.0     low
14  33856   10.5     low
15  33870   13.0     low
16  33908   14.0     low
17  33930   17.0     low

### Mark unsuitable essays

In [4]:
essay_scores_df["Suitable"] = essay_scores_df["Essay"] != "33083"

essay_scores_df

    Essay  Score    Band  Suitable
0   36560   28.0    high      True
1   44497   28.0    high      True
2   34811   26.0    high      True
3   37681   26.0    high      True
4   35240   25.0    high      True
5   34844   24.5    high      True
6   33493   18.0  medium      True
7   33083   20.0  medium     False
8   33991   21.5  medium      True
9   34292   19.0  medium      True
10  34841   23.0  medium      True
11  35121   21.0  medium      True
12  34714    8.0     low      True
13  33787    9.0     low      True
14  33856   10.5     low      True
15  33870   13.0     low      True
16  33908   14.0     low      True
17  33930   17.0     low      True

### Export `essay_scores_df`

In [5]:
essay_scores_df.to_markdown(
    "corpus/01_dataset_docs/essay_scores.md",
    index=False
)

## Processing 2

### Import essay scores from CSV

In [3]:
import pandas as pd

essay_scores_2_df = pd.read_csv(
    "corpus/01_dataset_docs/redacoes_coluna_A_constantes_no_word.csv",
    header=1
)

essay_scores_2_df

,INSCRICAO,REDACAO_TEMA,REDACAO_COLETANEA,REDACAO_TIPO_TEXTO,REDACAO_NORMA_CULTA,REDACAO_COESAO,REDACAO_COERENCIA,REDACAO_TOTAL
0,36560,"4,50","4,50","4,50","5,00","5,00","4,50","28,00"
1,44497,"4,00","4,00","5,00","5,00","5,00","5,00","28,00"
2,34811,"4,00","4,00","4,00","5,00","5,00","4,00","26,00"
3,37681,"4,50","4,00","4,00","4,50","5,00","4,00","26,00"
4,35240,"4,00","3,50","4,50","4,00","4,00","5,00","25,00"
5,34844,"3,00","3,00","4,00","5,00","5,00","4,50","24,50"
6,33493,"3,50","2,50","3,00","1,50","3,50","4,00","18,00"
7,33083,"2,50","2,50","3,50","4,50","3,50","3,50","20,00"
8,33991,"3,50","3,00","3,50","3,00","4,50","4,00","21,50"
9,34292,"4,00","4,00","4,00","3,00","0,00","4,00","19,00"
10,34841,"3,50","3,50","4,00","4,50","3,50","4,00","23,00"
11,35121,"4,00","3,50","2,50","4,00","3,00","4,00","21,00"
12,34714,"2,00","1,00","2,00","0,00","1,00","2,00","8,00"
13,33787,"1,00","1,00","2,00","1,00","3,00","1,00","9,00"
14,33856,"2,50","2,50","2,00","0,00","1,50","2,00","10,50"
15,33870,"2,00","2,50","2,00","0,00","3,00","3,50","13,00"
16,33908,"2,00","2,00","3,00","1,00","4,00","2,00","14,00"
17,33930,"3,00","2,50","3,00","2,00","3,50","3,00","17,00"

### Rename essay score columns

In [5]:
essay_scores_2_df.columns = [
    "Redação",
    "1. Adequação ao Tema",
    "2. Adequação à Coletânea (Projeto do Texto)",
    "3. Adequação ao tipo de texto",
    "4. Adequação à norma padrão",
    "5. Coesão",
    "6. Coerência",
    "Pontuação total",
]

essay_scores_2_df

,Redação,1. Adequação ao Tema,2. Adequação à Coletânea (Projeto do Texto),3. Adequação ao tipo de texto,4. Adequação à norma padrão,5. Coesão,6. Coerência,Pontuação total
0,36560,"4,50","4,50","4,50","5,00","5,00","4,50","28,00"
1,44497,"4,00","4,00","5,00","5,00","5,00","5,00","28,00"
2,34811,"4,00","4,00","4,00","5,00","5,00","4,00","26,00"
3,37681,"4,50","4,00","4,00","4,50","5,00","4,00","26,00"
4,35240,"4,00","3,50","4,50","4,00","4,00","5,00","25,00"
5,34844,"3,00","3,00","4,00","5,00","5,00","4,50","24,50"
6,33493,"3,50","2,50","3,00","1,50","3,50","4,00","18,00"
7,33083,"2,50","2,50","3,50","4,50","3,50","3,50","20,00"
8,33991,"3,50","3,00","3,50","3,00","4,50","4,00","21,50"
9,34292,"4,00","4,00","4,00","3,00","0,00","4,00","19,00"
10,34841,"3,50","3,50","4,00","4,50","3,50","4,00","23,00"
11,35121,"4,00","3,50","2,50","4,00","3,00","4,00","21,00"
12,34714,"2,00","1,00","2,00","0,00","1,00","2,00","8,00"
13,33787,"1,00","1,00","2,00","1,00","3,00","1,00","9,00"
14,33856,"2,50","2,50","2,00","0,00","1,50","2,00","10,50"
15,33870,"2,00","2,50","2,00","0,00","3,00","3,50","13,00"
16,33908,"2,00","2,00","3,00","1,00","4,00","2,00","14,00"
17,33930,"3,00","2,50","3,00","2,00","3,50","3,00","17,00"

### Export `essay_scores_2_df`

In [6]:
essay_scores_2_df.to_markdown(
    "corpus/01_dataset_docs/essay_scores_2.md",
    index=False
)